### PR TITLE
dotMailer API update

### PR DESCRIPTION
**Pull request by romanpitak**
Hi, there was a dotMailer API update.

### CODE REVIEW

**Comment by ishakuta** [comment]
@AlexandrDmitriev check if you need it

**Comment by romanpitak** [comment]
You might actually want to wait a bit. There have been quite a few updates to the API that are missing from the current implementation, but I'm working on them (together with some unit tests). 

I plan to have it done during November.

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for about an hour for the submission to be processed.

**Comment by mkudelya** [comment]
I am now closing this PR as, unfortunately, you have not signed our Contributor License Agreement. Please, feel free to reopen the issue and sign the CLA if you are still interested in this PR. Thank you!

**Pull request closed without merging**
